x-sam3d-base: &sam3d-base
  build:
    context: ../..
    dockerfile: modules/sam3d/Dockerfile
  volumes:
    - ../../modules/sam3d/data:/workspace/modules/sam3d/data
    - ../../modules/sam3d/data/checkpoints:/workspace/modules/sam3d/data/checkpoints
  environment:
    - CHECKPOINT_DIR=/workspace/modules/sam3d/data/checkpoints/hf-download
    - TORCH_HOME=/workspace/modules/sam3d/data/checkpoints/torch_home
    - HF_HOME=/workspace/modules/sam3d/data/checkpoints/hf_home
    - DATA_DIR=/data

services:
  sam3d-image-to-mesh:
    <<: *sam3d-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/sam3d/image_to_mesh.py"]

  sam3d-render-debug:
    <<: *sam3d-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/sam3d/render_debug_image.py"]
