params:
  seed: 0

  env:
    clip_observations: 10.0
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [1024, 1024, 512, 512]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None
    rnn:
      name: lstm
      units: 1024
      layers: 1
      before_mlp: True
      layer_norm: True

  load_checkpoint: False
  load_path: ''

  config:
    name: simtoolreal_clawhammer
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1
    reward_shaper:
      scale_value: 1.0  # env already applies reward_shaper_scale=0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.016
    score_to_win: 1000000
    max_epochs: 10000
    save_best_after: 100
    save_frequency: 500
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.1
    horizon_length: 16
    minibatch_size: 8192
    mini_epochs: 4
    critic_coef: 4.0
    clip_value: True
    seq_length: 16
    bounds_loss_coef: 0.0001

    player:
      deterministic: True
      games_num: 100000
      print_stats: True
