motion_file: source/robotic_grounding/robotic_grounding/assets/motion_data/object_pick_and_place_optimized_motion_with_ee.yaml

robot:
  type: g1  # Robot type for joint order lookup. Does not impact the robot asset spawned yet.
  qpos_key: qpos
  file_joint_order: isaaclab  # "mujoco", "isaaclab", or list of joint names. If "isaaclab", uses the robot's default ordering.
  anchor_offset: [0.0, 0.0, 0.06814659]
  ee_links:
    - left_hand_palm_link
    - right_hand_palm_link

target_object:
  name: object
  pos_offset: [0.0, 0.0, 0.06814659]
  scale: [1.0, 1.0, 1.0]

# fixed_objects: auto-discovered from HDF5 (any *_position keys except target)
fixed_objects:
  - name: table
    usd_path: source/robotic_grounding/robotic_grounding/assets/objects/ikea_4x2_shelf/ikea_4x2_shelf.usd
    position_key: table_position
    quaternion_key: table_wxyz
