motion_file: source/robotic_grounding/robotic_grounding/assets/motion_data/nvhuman_dex3/bottle_handover.parquet

robot:
  type: g1_dex3
  qpos_key: none # unsused
  file_joint_order: parquet
  anchor_offset: [0.0, 0.0, 0.68]
  ee_links:
    - left_hand_palm_link
    - right_hand_palm_link

target_object:
  name: bottle
  usd_path: source/robotic_grounding/robotic_grounding/assets/objects/bottle/bottle_physics.usda
  scale: [1.0, 1.0, 1.0]
  pos_offset: [0.0, 0.0, 0.68]
  position_key: object_translation
  quaternion_key: object_axis_angle

# Fixed objects in the scene
fixed_objects:
  - name: start_table
    usd_path: source/robotic_grounding/robotic_grounding/assets/objects/ikea_4x2_shelf/ikea_4x2_shelf.usd
    scale: [1.0, 1.0, 1.0]
    init_pos: [0.6747, -0.2047, 0.22]
    init_rot: [0.5, 0.5, 0.5, 0.5]

  - name: end_table
    usd_path: source/robotic_grounding/robotic_grounding/assets/objects/ikea_4x2_shelf/ikea_4x2_shelf.usd
    scale: [1.0, 1.0, 1.0]
    init_pos: [-1.6703, 0.0520, 0.22]
    init_rot: [0.5, 0.5, 0.5, 0.5]
