services:
include:
  - modules/moge/docker-compose.yaml
  - modules/unidepth/docker-compose.yaml
  - modules/sam2/docker-compose.yaml
  - modules/sam3d/docker-compose.yaml
  - modules/foundationpose/docker-compose.yaml
  - modules/nlf/docker-compose.yaml
