x-base-gpu: &base-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  volumes:
    - ./data:/data

x-base-cpu: &base-cpu
  volumes:
    - ./data:/data

services:
  ffmpeg:
    image: jrottenberg/ffmpeg
    volumes:
      - ./data:/data

  sam2-video-to-masks:
    build:
      context: .
      dockerfile: modules/sam2/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/sam2/checkpoints/sam2.1-hiera-large
    entrypoint: ["python", "/workspace/modules/sam2/video_to_masks.py"]

  sam2-annotate:
    build:
      context: .
      dockerfile: modules/sam2/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    entrypoint: ["python", "/workspace/modules/sam2/annotate.py"]

  moge-video-to-depth:
    build:
      context: .
      dockerfile: modules/moge/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/moge/checkpoints/moge-2-vitl-normal
    entrypoint: ["python", "/workspace/modules/moge/video_to_depth.py"]

  moge-image-to-depth:
    build:
      context: .
      dockerfile: modules/moge/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/moge/checkpoints/moge-2-vitl-normal
    entrypoint: ["python", "/workspace/modules/moge/image_to_depth.py"]

  unidepth-video-to-depth:
    build:
      context: .
      dockerfile: modules/unidepth/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/unidepth/checkpoints/unidepth-v2-vitl14
    entrypoint: ["python", "/workspace/modules/unidepth/video_to_depth.py"]

  unidepth-image-to-depth:
    build:
      context: .
      dockerfile: modules/unidepth/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/unidepth/checkpoints/unidepth-v2-vitl14
    entrypoint: ["python", "/workspace/modules/unidepth/image_to_depth.py"]

  sam3d-image-to-mesh:
    build:
      context: .
      dockerfile: modules/sam3d/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/sam3d/checkpoints/hf-download
      - TORCH_HOME=/data/sam3d/checkpoints/torch_home
      - HF_HOME=/data/sam3d/checkpoints/hf_home
    entrypoint: ["python", "/workspace/modules/sam3d/image_to_mesh.py"]

  sam3d-render-debug:
    build:
      context: .
      dockerfile: modules/sam3d/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/sam3d/checkpoints/hf-download
      - TORCH_HOME=/data/sam3d/checkpoints/torch_home
      - HF_HOME=/data/sam3d/checkpoints/hf_home
    entrypoint: ["python", "/workspace/modules/sam3d/render_debug_image.py"]

  foundationpose-video-to-poses:
    build:
      context: .
      dockerfile: modules/foundationpose/Dockerfile
    <<: *base-gpu
    shm_size: '14gb'
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/foundationpose/checkpoints/foundationpose
      - FOUNDATIONPOSE_WEIGHTS_DIR=/data/foundationpose/weights
    entrypoint: ["python", "/workspace/modules/foundationpose/video_to_poses.py"]

  foundationpose-align-mesh:
    build:
      context: .
      dockerfile: modules/foundationpose/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/foundationpose/checkpoints/foundationpose
      - FOUNDATIONPOSE_WEIGHTS_DIR=/data/foundationpose/weights
    entrypoint: ["python", "/workspace/modules/foundationpose/align_mesh_scale.py"]

  foundationpose-estimate-scale:
    build:
      context: .
      dockerfile: modules/foundationpose/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/foundationpose/checkpoints/foundationpose
      - FOUNDATIONPOSE_WEIGHTS_DIR=/data/foundationpose/weights
    entrypoint: ["python", "/workspace/modules/foundationpose/estimate_scale.py"]

  foundationpose-transform-mesh:
    build:
      context: .
      dockerfile: modules/foundationpose/Dockerfile
    <<: *base-cpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/foundationpose/checkpoints/foundationpose
      - FOUNDATIONPOSE_WEIGHTS_DIR=/data/foundationpose/checkpoints/weights
    entrypoint: ["python", "/workspace/modules/foundationpose/transform_mesh.py"]

  foundationpose-simplify-mesh:
    build:
      context: .
      dockerfile: modules/foundationpose/Dockerfile
    <<: *base-cpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/foundationpose/checkpoints/foundationpose
      - FOUNDATIONPOSE_WEIGHTS_DIR=/data/foundationpose/weights
    entrypoint: ["python", "/workspace/modules/foundationpose/simplify_mesh.py"]

  foundationpose-render-overlay:
    build:
      context: .
      dockerfile: modules/foundationpose/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - CHECKPOINT_DIR=/data/foundationpose/checkpoints/foundationpose
      - FOUNDATIONPOSE_WEIGHTS_DIR=/data/foundationpose/weights
    entrypoint: ["python", "/workspace/modules/foundationpose/render_overlay.py"]

  nlf-video-to-smpl:
    build:
      context: .
      dockerfile: modules/nlf/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - SMPL_MODEL_ROOT=/data/nlf/smpl_models
      - NLF_WEIGHTS_PATH=/data/nlf/weights/nlf_l_multi_0.3.2.torchscript
    entrypoint: ["python3", "modules/nlf/video_to_smpl.py"]

  nlf-render-smpl-overlay:
    build:
      context: .
      dockerfile: modules/nlf/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - SMPL_MODEL_ROOT=/data/nlf/smpl_models
      - NLF_WEIGHTS_PATH=/data/nlf/weights/nlf_l_multi_0.3.2.torchscript
    entrypoint: ["python3", "modules/nlf/render_smpl_overlay.py"]

  nlf-align-to-depth:
    build:
      context: .
      dockerfile: modules/nlf/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - SMPL_MODEL_ROOT=/data/nlf/smpl_models
      - NLF_WEIGHTS_PATH=/data/nlf/weights/nlf_l_multi_0.3.2.torchscript
    entrypoint: ["python3", "modules/nlf/align_nlf_to_depth.py"]

  nlf-align-depth-to-smpl:
    build:
      context: .
      dockerfile: modules/nlf/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - SMPL_MODEL_ROOT=/data/nlf/smpl_models
      - NLF_WEIGHTS_PATH=/data/nlf/weights/nlf_l_multi_0.3.2.torchscript
    entrypoint: ["python3", "modules/nlf/align_depth_to_smpl.py"]

  nlf-render-smpl-depth:
    build:
      context: .
      dockerfile: modules/nlf/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - SMPL_MODEL_ROOT=/data/nlf/smpl_models
      - NLF_WEIGHTS_PATH=/data/nlf/weights/nlf_l_multi_0.3.2.torchscript
    entrypoint: ["python3", "modules/nlf/render_smpl_depth.py"]

  grounding-dino-image-to-object-bboxes:
    build:
      context: .
      dockerfile: modules/grounding_dino/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - MODEL_DIR=/data/grounding_dino/models
    entrypoint: ["python", "/workspace/modules/grounding_dino/image_to_object_bboxes.py"]

  grounding-dino-image-list-to-object-bboxes:
    build:
      context: .
      dockerfile: modules/grounding_dino/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - MODEL_DIR=/data/grounding_dino/models
    entrypoint: ["python", "/workspace/modules/grounding_dino/image_list_to_object_bboxes.py"]

  grounding-dino-video-to-object-bboxes:
    build:
      context: .
      dockerfile: modules/grounding_dino/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - MODEL_DIR=/data/grounding_dino/models
    entrypoint: ["python", "/workspace/modules/grounding_dino/video_to_object_bboxes.py"]

  foundation-stereo-image-list-to-depth:
    build:
      context: .
      dockerfile: modules/foundation_stereo/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - MODEL_DIR=/data/foundation_stereo/models
    entrypoint: ["python", "/workspace/modules/foundation_stereo/image_list_to_depth.py"]

  foundation-stereo-image-to-depth:
    build:
      context: .
      dockerfile: modules/foundation_stereo/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
      - MODEL_DIR=/data/foundation_stereo/models
    entrypoint: ["python", "/workspace/modules/foundation_stereo/image_to_depth.py"]

  viz:
    build:
      context: .
      dockerfile: viz/Dockerfile
    <<: *base-gpu
    environment:
      - DATA_DIR=/data
    entrypoint: ["python", "viz/app.py"]