x-moge-base: &moge-base
  build:
    context: ../..
    dockerfile: modules/moge/Dockerfile
  volumes:
    - ../../modules/moge/data:/workspace/modules/moge/data
  environment:
    - CHECKPOINT_DIR=/workspace/modules/moge/data/checkpoints/moge-2-vitl-normal
    - DATA_DIR=/data

services:
  moge-video-to-depth:
    <<: *moge-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/moge/video_to_depth.py"]

  moge-image-to-depth:
    <<: *moge-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/moge/image_to_depth.py"]
