services:
  base-gpu:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../data:/data

  base-cpu:
    volumes:
      - ../data:/data

  base-api:
    extends:
      service: base-cpu
    # Ports should be defined in each module's compose file

