x-sam2-base: &sam2-base
  build:
    context: ../..
    dockerfile: modules/sam2/Dockerfile
  volumes:
    - ../../modules/sam2/data/checkpoints:/workspace/modules/sam2/data/checkpoints
    - ../../modules/sam2/data:/workspace/modules/sam2/data
  environment:
    - CHECKPOINT_DIR=/workspace/modules/sam2/data/checkpoints/sam2.1-hiera-large
    - REDIS_URL=redis://redis:6379/0

services:
  sam2-video-to-masks-test:
    <<: *sam2-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    volumes:
      - ../../modules/sam2/tests/test_data:/workspace/modules/sam2/tests/test_data
      - ../../modules/sam2/data/checkpoints:/workspace/modules/sam2/data/checkpoints
    command: [
      "python", 
      "/workspace/modules/sam2/functions/video_to_masks.py", 
      "--video_path", "/workspace/modules/sam2/tests/test_data/test_video.mp4", 
      "--prompts_path", "/workspace/modules/sam2/tests/test_data/test_prompts.json", 
      "--masks_dir", "/workspace/modules/sam2/tests/test_data/output/test_masks"
    ]
    profiles: ["tests"]

  sam2-video-to-masks:
    <<: *sam2-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/sam2/functions/video_to_masks.py"]
    profiles: ["exec"]

  sam2-video-to-masks-worker:
    <<: *sam2-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    depends_on:
      - redis
    command: ["celery", "-A", "modules.sam2.worker", "worker", "--loglevel=info", "-Q", "sam2.video_to_masks", "--concurrency=1", "--prefetch-multiplier=1"]
    profiles: ["workers", "api"]

  sam2-api:
    <<: *sam2-base
    extends:
      file: ../common-compose.yaml
      service: base-api
    ports:
      - "8001:8001"
    command: ["python", "/workspace/modules/sam2/api.py"]
    depends_on:
      - redis
    profiles: ["api"]
