x-fp-base: &fp-base
  build:
    context: ../..
    dockerfile: modules/foundationpose/Dockerfile
  volumes:
    - ../../modules/foundationpose/extra/FoundationPose:/workspace/FoundationPose
    - ../../modules/foundationpose/data:/workspace/modules/foundationpose/data
    - ../../modules/foundationpose/third_party/FoundationPose/weights:/workspace/modules/foundationpose/third_party/FoundationPose/weights
  environment:
    - CHECKPOINT_DIR=/workspace/modules/foundationpose/data/checkpoints/foundationpose
    - WEIGHTS_DIR=/workspace/modules/foundationpose/data/checkpoints/weights
    - DATA_DIR=/data

services:
  foundationpose-video-to-poses:
    <<: *fp-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    shm_size: '14gb'
    entrypoint: ["python", "/workspace/modules/foundationpose/video_to_poses.py"]

  foundationpose-align-mesh:
    <<: *fp-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/foundationpose/align_mesh_scale.py"]

  foundationpose-transform-mesh:
    <<: *fp-base
    extends:
      file: ../common-compose.yaml
      service: base-cpu
    entrypoint: ["python", "/workspace/modules/foundationpose/transform_mesh.py"]

  foundationpose-simplify-mesh:
    <<: *fp-base
    extends:
      file: ../common-compose.yaml
      service: base-cpu
    entrypoint: ["python", "/workspace/modules/foundationpose/simplify_mesh.py"]

  foundationpose-render-overlay:
    <<: *fp-base
    extends:
      file: ../common-compose.yaml
      service: base-gpu
    entrypoint: ["python", "/workspace/modules/foundationpose/render_foundationpose_overlay.py"]
